apiVersion: v1
kind: Service
metadata:
  name: ship-www
  labels:
    app: ship-www
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30065
    port: 3000
    targetPort: http
  selector:
    app: ship-www

