---
baseURL: "/"
languageCode: "en-us"
title: "Replicated Ship"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation and knowledgebase for Replicated Ship."
googleAnalytics: "UA-61084834-1"

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"
  search_env: "staging"

  favicon: ""
  pagetitle: "Replicated"
  permalink: "#"

algolia:
  index: "ship_staging"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Documentation"
      Weight: 2
      URL: "/docs/getting-started"
---
