apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-www
spec:
  template:
    spec:
      containers:
        - name: ship-www
          image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/ship-www
