apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-www
spec:
  selector:
    matchLabels:
      app: ship-www
  template:
    metadata:
      labels:
        app: ship-www
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ship-cloud-api
              topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ship-www
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      containers:
        - name: ship-www
          image: gcr.io/replicated-qa/ship-www
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
