apiVersion: v1
kind: Service
metadata:
  name: ship-www
  labels:
    app: ship-www
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8065
    targetPort: http
  selector:
    app: ship-www

